version: '3.8'

services:

  app:
    image: ekyc
    restart: always
    container_name: ekyc
    ports:
     - "8080:8080"

  face_match_worker:
    image: face_match_worker
    restart: always
    container_name: face_match_worker

  db:
    image: postgres
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_EXTENSIONS: uuid-ossp
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  test_db:
    image: postgres
    container_name: test_postgresql
    restart: always
    environment:
      POSTGRES_USER: test_postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_EXTENSIONS: uuid-ossp
    volumes:
      - testpgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: mohit@one2n.in
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  minio:
    image: "minio/minio"
    restart: always
    container_name: minio
    ports:
      - "9000:9000"
      - "9099:9099"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server --address ":9099" --console-address ":9000" /data
    volumes:
      - "minio_data:/data"

  redis:
    restart: always
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmq:/var/lib/rabbitmq/
        - rabbitmq:/var/log/rabbitmq

volumes:
  pgdata:
  pgadmin-data:
  testpgdata:
  minio_data:
  redis_data:
  rabbitmq: